---
title: "Models"
date: "2024-10-01"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r libraries, include = FALSE}
library(data.table)
library(tidyverse)
library(ggplot2)
library(knitr)
library(reshape2)
library(stats)
library(DescTools)
library(brglm2)
library(car)
library(kableExtra)
knitr::opts_chunk$set(out.extra='style="font-size: 8px;"')
load('/home/idiap/projects/TFG_sentinella/dades.RData')
```

```{r, include=FALSE}
taula_post = taula %>% select(contains('_F')|contains('_S'))
taula_post = taula_post %>% select(-PHYSICAL_FATIGUE, -MAAS_score, -PHQ_score, -GAD_score, -COGNITIVE_FATIGUE)

taula_post_columns <- colnames(taula_post)

cleaned_taulapost_columns <- gsub("(_F|_S|_s)$", "", taula_post_columns)

taulapre_columns <- colnames(taula)

matching_columns <- intersect(cleaned_taulapost_columns, taulapre_columns)

taula_pre <- taula %>% select(all_of(matching_columns))
setnames(taula_post, gsub("_F$|_S$|_s$", "", names(taula_post)))

variables_test_num = c('PHQ_score', 'GAD_score', 'SMBM_mean')
variables_test_num2 = c('Midtgaard_total', 'AUDIT_total', 'MAAS_score', 'OSS_total', 'DAST1')
```

* Variance Inflation Factors test to know which variables have the highest multicollinearity for the regression analysis

```{r, echo=FALSE}
taula2 = taula %>% mutate(nova = taula_post$Midtgaard_total-taula_pre$Midtgaard_total)
  model = lm(taula2$nova ~ taula$SENTINEL + taula$SEX + taula$`SEXUAL ORIENTATION` + taula$`LIVING SITUATION` + taula$RELATIONSHIP + taula$FINANCING + taula$CCAA + taula$`HEALTHCARE WORKING PARENTS`+ taula$PHSYCHIATRY+ taula$AGE + taula$YEAR + taula$GENDER + taula$EMPLOYMENT + taula$midtgaard_change + taula$audit_change + taula$oss_change + taula$DAST1_change + taula$PHQ_change + taula$GAD_change +
               taula$SMBM_change + taula$MENTAL_HEALTH_DIAGNOSIS_change + taula$MENTAL_HEALTH_TREATMENT_change + taula$MENTAL_HEALTH_FAMILY_HISTORY + taula$`SENTINEL CONSULT` + taula$`SENTINEL MEETINGS` + taula$`MENTAL HEALTH USEFULNESS` + taula$`WELLBEING USEFULNESS`)
  vif(model)
```

* Resultat després d'eliminar les variables amb més colinearitat

```{r, echo=FALSE}
taula2 = taula %>% mutate(nova = taula_post$Midtgaard_total-taula_pre$Midtgaard_total)
  model = lm(taula2$nova ~ taula$SENTINEL + taula$`SEXUAL ORIENTATION` + taula$`LIVING SITUATION` + taula$RELATIONSHIP + taula$FINANCING + taula$CCAA + taula$`HEALTHCARE WORKING PARENTS`+ taula$PHSYCHIATRY + taula$GENDER + taula$EMPLOYMENT + taula$midtgaard_change + taula$audit_change + taula$oss_change + taula$DAST1_change + taula$PHQ_change + taula$GAD_change + taula$SMBM_change  + taula$MENTAL_HEALTH_DIAGNOSIS_change + taula$MENTAL_HEALTH_FAMILY_HISTORY + taula$`MENTAL HEALTH USEFULNESS` + taula$`WELLBEING USEFULNESS`)
  vif(model)
```

* Models per PHQ, GAD i SMBM

```{r, warning=FALSE}
for (i in variables_test_num) {
  print(i)
  taula2 = taula %>% mutate(nova = taula_post[[i]]-taula_pre[[i]]) # Creem variable nova que sigui la diferència entre el post i el pre
  model = lm(taula2$nova ~ taula$SENTINEL + taula$GENDER + taula$`SEXUAL ORIENTATION` + taula$`LIVING SITUATION` + taula$RELATIONSHIP + taula$FINANCING + taula$CCAA + taula$`HEALTHCARE WORKING PARENTS`+ taula$PHSYCHIATRY + taula$EMPLOYMENT + taula$midtgaard_change + taula$audit_change + taula$oss_change + taula$DAST1_change + taula$MENTAL_HEALTH_DIAGNOSIS_change + taula$MENTAL_HEALTH_FAMILY_HISTORY + taula$`MENTAL HEALTH USEFULNESS` + taula$`WELLBEING USEFULNESS`) # Eliminem edat, curs, sexe ja que eren les variables amb més multicolinearitat
  modelfinal = Anova(model, type = "II")
  print(modelfinal)
  cat('\n')
  cat('--------------------------------------------------------')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
}

```

* Resta de models

```{r, warning=FALSE}
for (i in variables_test_num2) {
  print(i)
  taula2 = taula %>% mutate(nova = taula_post[[i]]-taula_pre[[i]]) # Creem variable nova que sigui la diferència entre el post i el pre
  model = lm(taula2$nova ~ taula$SENTINEL + taula$GENDER + taula$`SEXUAL ORIENTATION` + taula$`LIVING SITUATION` + taula$RELATIONSHIP + taula$FINANCING + taula$CCAA + taula$`HEALTHCARE WORKING PARENTS`+ taula$PHSYCHIATRY + taula$EMPLOYMENT + taula$MENTAL_HEALTH_DIAGNOSIS_change + taula$MENTAL_HEALTH_FAMILY_HISTORY + taula$`MENTAL HEALTH USEFULNESS` + taula$`WELLBEING USEFULNESS`) # Eliminem edat, curs, sexe ja que eren les variables amb més multicolinearitat
  modelfinal = Anova(model, type = "II")
  print(modelfinal)
  cat('\n')
  cat('--------------------------------------------------------')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
  cat('\n')
}

```
