---
title: "prepost"
date: "2024-10-01"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r libraries, include = FALSE}
library(data.table)
library(tidyverse)
library(ggplot2)
library(knitr)
library(reshape2)
library(stats)
library(DescTools)
load('/home/idiap/projects/TFG_sentinella/dades.RData')
```

```{r, include=FALSE}
taula_post = taula %>% select(contains('_F')|contains('_S'))
taula_post = taula_post %>% select(-PHYSICAL_FATIGUE, -MAAS_score, -PHQ_score, -GAD_score, -COGNITIVE_FATIGUE)

taula_post_columns <- colnames(taula_post)

cleaned_taulapost_columns <- gsub("(_F|_S|_s)$", "", taula_post_columns)

taulapre_columns <- colnames(taula)

matching_columns <- intersect(cleaned_taulapost_columns, taulapre_columns)

taula_pre <- taula %>% select(all_of(matching_columns))
setnames(taula_post, gsub("_F$|_S$|_s$", "", names(taula_post)))

taula_pre2 = taula_pre %>% mutate(MAAS_score = round(as.numeric(MAAS_score),0)) %>% 
  mutate(PHYSICAL_FATIGUE = round(as.numeric(PHYSICAL_FATIGUE),0)) %>% 
  mutate(COGNITIVE_FATIGUE = round(as.numeric(COGNITIVE_FATIGUE),0)) %>% 
  mutate(SMBM_mean = round(as.numeric(SMBM_mean),0)) %>% 
  mutate(EMOTIONAL_EXAHUSTION = round(as.numeric(EMOTIONAL_EXAHUSTION),0))

taula_post2 = taula_post %>% mutate(MAAS_score = round(as.numeric(MAAS_score),0)) %>% 
  mutate(PHYSICAL_FATIGUE = round(as.numeric(PHYSICAL_FATIGUE),0)) %>% 
  mutate(COGNITIVE_FATIGUE = round(as.numeric(COGNITIVE_FATIGUE),0)) %>% 
  mutate(SMBM_mean = round(as.numeric(SMBM_mean),0)) %>% 
  mutate(EMOTIONAL_EXAHUSTION = round(as.numeric(EMOTIONAL_EXAHUSTION),0))

variables_bin = c('SENTINEL', 'Midtgaard1',  'Midtgaard2',  'Midtgaard3',  'Midtgaard5',  'Midtgaard6',  'Midtgaard7',  'Midtgaard8',  'Midtgaard9',
                  'Midtgaard10',  'Midtgaard11',  'Midtgaard12',  'Midtgaard13', 'DAST1', 'MENTAL HEALTH DIAGNOSIS', 'MENTAL HEALTH TREATMENT', 'SMBM_recorded',
                  'MHS KNOWLEDGE', 'MHS1 ACCESS', 'MHS2 ACCESS', 'MHS3 ACCESS', 'MHS4 ACCESS', 'MHS5 ACCESS', 'MHS6 ACCESS', 'AUDIT_cat', 'PHQ_recoded', 'GAD_recoded')
variables_num = c('MAAS_score', 'PHYSICAL_FATIGUE', 'COGNITIVE_FATIGUE', 'SMBM_mean', 'EMOTIONAL_EXAHUSTION', 'OSS1', 'OSS2', 'OSS3', 'OSS_total',
                  'AUDIT1', 'AUDIT2', 'AUDIT3', 'AUDIT_total', 'MAAS1', 'MAAS2', 'MAAS3', 'MAAS4', 'MAAS5', 'MAAS6', 'MAAS7', 'MAAS8', 'MAAS9', 'MAAS10', 'MAAS11', 
                  'MAAS12', 'MAAS13', 'MAAS14', 'MAAS15', 'PHQ1', 'PHQ2', 'PHQ3', 'PHQ4', 'PHQ5', 'PHQ6', 'PHQ7', 'PHQ8', 'PHQ9', 'GAD1', 'GAD2', 'GAD3', 'GAD4', 
                  'GAD5', 'GAD6', 'GAD7', 'SMBM1', 'SMBM2', 'SMBM3', 'SMBM4', 'SMBM5', 'SMBM6', 'SMBM7', 'SMBM8', 'SMBM9', 'SMBM10', 'SMBM11', 'SMBM12', 'SMBM13', 'SMBM14', 
                  'GAD_score', 'Midtgaard_total', 'PHQ_score', 'MEDICAL SCHOOL ENVIRONMENT')
```

```{r, results='asis', warning=FALSE}
for (i in names(taula_pre[, -1])) {       # La primera variable es la identificativa, aixi que no la tenim en conte
  cat(sprintf("\n\n## %s \n\n", i))
    
  # Creem taula de contingencia
  contingency_table <- table(taula_pre2[[i]], taula_post2[[i]])
    
  df <- as.data.frame(as.table(contingency_table))
    
    # Creem heatmap de les taules anteriors
    p <- ggplot(df, aes(Var1, Var2)) +
      geom_tile(aes(fill = Freq), color = "white") + 
      geom_text(aes(label = Freq), color = "black", size = 5) +  # Pasar valors dins els quadrats
      scale_fill_gradient(low = "white", high = "steelblue") +
      labs(title = paste("Heatmap for Variable", i),
           x = "taula_pre", y = "taula_post", fill = "Count") +
      guides(fill = "none") +
      theme_minimal()
    
    print(p)
    if (i%in%variables_bin) {
      print('Mcnemar test:')
      print(mcnemar.test(table(as.character(taula_pre[[i]]), as.character(taula_post[[i]])))$p.value)
    } else if (i%in%variables_num) {
      print('p-values GTest:')
      print(GTest(table(taula_pre[[i]], taula_post[[i]]))$p.value)
      cat('\n')
      print('CramerV test')
      print(CramerV(table(taula_pre[[i]], taula_post[[i]])))
    } else if (i == 'Midtgaard4' | i == 'Midtgaard14') {
      print('Not computable') }
      else {
      print('CochranQTest:')
      print(CochranQTest(cbind(taula_pre[[i]], taula_post[[i]]))$p.value)
    }
    cat("\n")  
  }
```